CREATE TABLE daily_prospects (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  batch_date DATE NOT NULL,
  zone VARCHAR(120) NULL,
  city VARCHAR(120) NULL,
  province VARCHAR(120) NULL,
  agency_name VARCHAR(255) NOT NULL,
  phone VARCHAR(80) NULL,
  email VARCHAR(255) NULL,
  website VARCHAR(500) NULL,
  address VARCHAR(500) NULL,
  source_url VARCHAR(700) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pendiente',
  notes TEXT NULL,
  follow_up_at DATETIME NULL,
  contacted_at DATETIME NULL,
  converted_contact_id BIGINT NULL,
  normalized_key VARCHAR(500) NOT NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_prospect_tenant_key (tenant_id, normalized_key(250)),
  INDEX idx_prospect_batch (tenant_id, batch_date),
  INDEX idx_prospect_status (tenant_id, status)
);

INSERT IGNORE INTO daily_prospects
(tenant_id,batch_date,zone,city,province,agency_name,phone,email,website,address,source_url,normalized_key,created_by)
VALUES
(1,CURDATE(),'El Aljarafe','Almensilla','Sevilla','Grupo Jabel','661 226 095','direccion@grupojabel.com','https://www.grupojabel.es','Calle Prado, 2A, 41111 Almensilla','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','grupo jabel|almensilla|661226095',1),
(1,CURDATE(),'El Aljarafe','Aznalcázar','Sevilla','Román Inmobiliaria Aznalcázar','955 750 000','info@romaninmobiliaria.es','https://www.romaninmobiliaria.es','Calle Muralla, 11, 41849 Aznalcázar','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','roman inmobiliaria aznalcazar|aznalcazar|955750000',1),
(1,CURDATE(),'El Aljarafe','Benacazón','Sevilla','Román Inmobiliaria Benacazón','955 750 000','info@romaninmobiliaria.es','https://www.romaninmobiliaria.es','Calle San Sebastián, 40, 41805 Benacazón','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','roman inmobiliaria benacazon|benacazon|955750000',1),
(1,CURDATE(),'El Aljarafe','Bollullos de la Mitación','Sevilla','Bollullos Inmobiliaria 2005','955 766 352',NULL,'https://www.bollullosinmobiliaria2005.es','Av. de la Constitución, 60, 41110 Bollullos de la Mitación','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','bollullos inmobiliaria 2005|bollullos de la mitacion|955766352',1),
(1,CURDATE(),'El Aljarafe','Bormujos','Sevilla','RE/MAX Finanbank','650 758 580','finanbank@remax.es','https://www.remax.es','Calle 28 de Febrero, local 1, 41930 Bormujos','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','re max finanbank|bormujos|650758580',1),
(1,CURDATE(),'El Aljarafe','Bormujos','Sevilla','Inmotrebol Asesores Inmobiliarios','954 788 475','info@inmotrebol.es','https://www.inmotrebol.es','C/ Pablo Coso Calero, 74, 41930 Bormujos','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','inmotrebol asesores inmobiliarios|bormujos|954788475',1),
(1,CURDATE(),'El Aljarafe','Bormujos','Sevilla','Fincas M & M Inmobiliaria','954 788 828','fincasmyminmo@gmail.com','https://www.fincasmym.es','Av. Salamanca, 10, Local 10, 41930 Bormujos','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','fincas m m inmobiliaria|bormujos|954788828',1),
(1,CURDATE(),'El Aljarafe','Camas','Sevilla','Estudio Camas Gestión 2020','955 231 384',NULL,'https://www.tecnocasa.es','Av. Santa María de Gracia, 64, 41900 Camas','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','estudio camas gestion 2020|camas|955231384',1),
(1,CURDATE(),'El Aljarafe','Camas','Sevilla','Solhogar Inmobiliaria','955 989 160','antonio@solhogar.com','https://www.solhogar.com','C/ Joaquín Camino, 5 local, 41900 Camas','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','solhogar inmobiliaria|camas|955989160',1),
(1,CURDATE(),'El Aljarafe','Gelves','Sevilla','Estudio Gelves Aljarafe','604 968 131',NULL,'https://www.tecnocasa.es','C/ Real, 38, Local, 41120 Gelves','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','estudio gelves aljarafe|gelves|604968131',1),
(1,CURDATE(),'El Aljarafe','Gelves','Sevilla','KamarAljarafe','693 854 310','info@kamaraljarafe.com','https://www.kamaraljarafe.com','C/ Progreso, 17, 2º, 41120 Gelves','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','kamaraljarafe|gelves|693854310',1),
(1,CURDATE(),'El Aljarafe','Olivares','Sevilla','Aljasur Gestión Inmobiliaria','954 111 481',NULL,'https://www.aljasurgestioninmobiliaria.com','Av. Virgen del Rocío, 1, 41804 Olivares','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','aljasur gestion inmobiliaria|olivares|954111481',1),
(1,CURDATE(),'El Aljarafe','Pilas','Sevilla','Sparta Grupo Inmobiliario','955 312 121',NULL,'https://www.spartainmobiliaria.com','C/ Virgen de Fátima, 11, 41840 Pilas','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','sparta grupo inmobiliario|pilas|955312121',1),
(1,CURDATE(),'El Aljarafe','Umbrete','Sevilla','Álvaro Ruiz Inmobiliaria','955 714 000','info@alvaroruizinmobiliaria.es','https://www.alvaroruizinmobiliaria.es','C/ Real, 10, 41806 Umbrete','https://aljarafe5sentidos.com/inmobiliarias-del-aljarafe/','alvaro ruiz inmobiliaria|umbrete|955714000',1),
(1,CURDATE(),'El Aljarafe','Salteras','Sevilla','Asinsal','955 707 152',NULL,NULL,'C/ Horno, 1, 41909 Salteras','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','asinsal|salteras|955707152',1),
(1,CURDATE(),'El Aljarafe','Espartinas','Sevilla','Agencia Nancy Inmobiliaria','610 142 315','info@nancyinmobiliaria.es',NULL,'C. Torre de la Plata, 3, 41807 Espartinas','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','agencia nancy inmobiliaria|espartinas|610142315',1),
(1,CURDATE(),'El Aljarafe','Gines','Sevilla','InmoFinK Gestión Inmobiliaria','955 980 580','info@inmofink.es',NULL,'Av. San José, 23, 41960 Gines','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','inmofink gestion inmobiliaria|gines|955980580',1),
(1,CURDATE(),'El Aljarafe','Gines','Sevilla','Deco Aljarafe Inmobiliaria','954 163 434','salvador@deco.es',NULL,'Av. de Europa, 17, 41960 Gines','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','deco aljarafe inmobiliaria|gines|954163434',1),
(1,CURDATE(),'El Aljarafe','Bormujos','Sevilla','Habitalia Sur Gestión Inmobiliaria','955 278 033','habitalia@habitaliasur.com',NULL,'Av. República Argentina, 29, 41930 Bormujos','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','habitalia sur gestion inmobiliaria|bormujos|955278033',1),
(1,CURDATE(),'El Aljarafe','Castilleja de la Cuesta','Sevilla','Inmobiliaria Charo','954 161 523','info@inmobiliariacharo.com','https://www.inmobiliariacharo.com','C/ Diego de los Reyes, 179, 41950 Castilleja de la Cuesta','https://agenciasinmobiliarias.com.es/es-es/z/inmobiliarias/55-el-aljarafe/','inmobiliaria charo|castilleja de la cuesta|954161523',1);
