CREATE TABLE IF NOT EXISTS personal_hub_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  owner_id INT NOT NULL,
  section ENUM('inbox','task','agenda','resource') NOT NULL,
  title VARCHAR(240) NOT NULL,
  body TEXT NULL,
  task_status ENUM('por_hacer','hoy','en_proceso','esperando','hecho') NULL,
  scheduled_start DATETIME NULL,
  scheduled_end DATETIME NULL,
  resource_url VARCHAR(1000) NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'user',
  position INT NOT NULL DEFAULT 0,
  metadata JSON NULL,
  completed_at DATETIME NULL,
  created_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_personal_hub_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_personal_hub_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_personal_hub_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_personal_hub_section (tenant_id, owner_id, section, position),
  INDEX idx_personal_hub_tasks (tenant_id, owner_id, task_status, position),
  INDEX idx_personal_hub_agenda (tenant_id, owner_id, scheduled_start)
);
